class RouteNames {
  RouteNames._();
  static const selectedMethodLogin = '/selected-method-login';
  static const signUp = '/sign-up';
  static const logIn = '/log-in';
  static const universitySelection = '/university-selection';
  static const otpScreen = '/otp-screen';
  static const forgetPassword = '/forget-password';
  static const resetPassword = '/reset-password';
  static const viedioPage = '/video';
  static const cachedVideos = '/cached-videos';
  static const courceInf = '/cource-inf';
  static const courses = '/courses';
  static const chapterPage = '/chapter-page';
  static const quizPage = '/quiz-Page';
  static const profile = '/profile';
  static const homePage = '/home-page';
  static const viewAllArticles = '/view-all-articles';
  static const viewAllTeachers = '/view-all-teachers';
  static const viewAllCourses = '/view-all-courses';
  static const aticleDetails = '/article-details';
  static const mainHomePage = '/rt';
  static const teatcherPage = '/teatcher-page';
  static const searchPage = '/';
  static const savedCourses = '/saved-courses';
  static const downloads = '/downloads';
  static const aboutUs = '/about-us';
  static const privacy = '/privacy-policy';
  static const term = '/term';
  static const enroll = '/enroll';
  static const noInternet = '/no-internet';
}
