


// ignore_for_file: constant_identifier_names

enum EmptyPageType {
  ERROR_403,
  ERROR_500,
  NO_INTERNET,
  NO_SALON_SERVICES,
  NO_SALON_REVIEWS,
  NO_CATEGORY_SERVICES,
  NO_FAVOURITE_ITEMS,
  NO_NEAREST_SERVICES,
  NO_SEARCH_FOUND,}

enum AppDialogType {
  ERROR_DIALOG,
  CANCEL_SERVICE_DIALOG,
  LOGOUT_DIALOG,
  DELETE_ACCOUNT_DIALOG,
  SUCCESS_SERVICE_BOOKING_DIALOG,
  CANCEL_BOOKING_DIALOG,
  CANCEL_EDITING_PROFILE_DIALOG,
  NO_BOOKING_AVAILABLE_DIALOG,
  DELETE_COMMENT_DIALOG,
}

enum RequestType { GET, PUT, POST, DELETE }

enum ExceptionCode {
  PHONE_ALREADY_TAKEN,
  CASH,
  HTTP,
  UNKNOWN,
  NO_INTERNET,
  MISSING_MEDIA,
  LOCATION_ACCESS,
  NO_PERMISSION,
  MAPPING,
  OTPNOTCOMPLETED,
  FIREBASE,
  USER_NOT_FOUND,
  WRONG_DATA,
  CANCELED_BY_USER,
  WRONG_EMAIL_PASSWORD,
  DOWNLOADING,
  SAVING_IMAGE_TO_GALLERY,
  MISIING_DATA
}
